server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  location = /install.sh {
    default_type text/plain;
    add_header Cache-Control "no-cache";
    add_header Content-Disposition 'inline; filename="install.sh"';
  }
  location = /install.ps1 {
    default_type text/plain;
    add_header Cache-Control "no-cache";
    add_header Content-Disposition 'inline; filename="install.ps1"';
  }
  location / {
    try_files $uri $uri/ /index.html;
  }
}
